#!/usr/bin/env bash
#Track which web server is answering our http requests.
apt-get update
apt-get -y install nginx
HOST=$(cat /etc/hostname)
sed -i "/listen \[::\]:80 default_server;/a \\\n\tadd_header X-Served-By \"$HOST\";" /etc/nginx/sites-enabled/default
service nginx restart
