#!/usr/bin/env bash
# Make Ngnix server listen to port 80 through debugging.
sudo rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
