#!/usr/bin/env bash
# Manages my process.
if [ "$1" == "start" ]; then

    ./manage_my_process &
    sudo bash -c "echo $BASHPID > /var/run/my_process.pid"
    echo "manage_my_process started"

elif [ "$1" == "stop" ]; then

    pkill -f -SIGTERM "./manage_my_process"
    sudo rm /var/run/my_process.pid
    echo "manage_my_process stopped"

elif [ "$1" == "restart" ]; then

    pkill -f -SIGTERM "./manage_my_process"
    sudo rm /var/run/my_process.pid
    ./manage_my_process &
    sudo bash -c "echo $BASHPID > /var/run/my_process.pid"
    echo "manage_my_process restarted"

else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
