#!/usr/bin/env bash
# display displays Holberton School with some differences
ite=1
while [ $ite -le 10 ]
do
  echo "Holberton School"
  ite=$((ite + 1))
  if [ $ite -eq 10 ]
  then
      echo "Hi"
  fi
done
