#!/usr/bin/env bash
# Exo for Holberton School
ite=1
while [ $ite -le 10 ]
do
  if [ $ite -eq 4 ]; then
      echo "bad luck"
  elif [ $ite -eq 8 ]; then
      echo "good luck"
  else
      echo "Holberton School"
  fi
  ite=$((ite + 1))
done
