#!/usr/bin/env bash
# Exercise for Holberton School
ite=1
while [ $ite -le 20 ]
do
  echo $ite
  case $ite in
      4)
	  echo "bad luck from China"
	  ;;
      9)
	  echo "bad luck from Japan"
	  ;;
      17)
	  echo "bad luck from Italy"
	  ;;
  esac
  ite=$((ite + 1))
done
